const pool = [
    {
        id: 1,
        name: "NFTx APO",
        apr: 1.0,
        tvl: 1.10,
        earned: 1.11,
    },
    {
        id: 2,
        name: "NFTx APO",
        apr: 0.0,
        tvl: 0.0,
        earned: 0.0,
    },
    {
        id: 3,
        name: "NFTx APO",
        apr: 0.0,
        tvl: 0.0,
        earned: 0.0,
    },
    {
        id: 4,
        name: "NFTx APO",
        apr: 0.0,
        tvl: 0.0,
        earned: 0.0,
    },
    {
        id: 5,
        name: "NFTx APO",
        apr: 0.0,
        tvl: 0.0,
        earned: 0.0,
    },
    {
        id: 6,
        name: "NFTx APO",
        apr: 0.0,
        tvl: 0.0,
        earned: 0.0,
    },
    {
        id: 7,
        name: "NFTx APO",
        apr: 0.0,
        tvl: 0.0,
        earned: 0.0,
    },
    {
        id: 8,
        name: "NFTx APO",
        apr: 0.0,
        tvl: 0.0,
        earned: 0.0,
    },
    {
        id: 9,
        name: "NFTx APO",
        apr: 0.0,
        tvl: 0.0,
        earned: 0.0,
    },
]
